package paladinus.util;

public enum ActionSelectionRule {
	NONE,
	
	MIN_H,
	MIN_H_TIMES_CHILDREN_SIZE,
	MIN_H_POWER_CHILDREN_SIZE,
	
	MIN_SUM_H,
	MIN_SUM_H_TIMES_CHILDREN_SIZE,
	MIN_SUM_H_POWER_CHILDREN_SIZE,
	
	MEAN_H, 
	MAX_AVG_H_VALUE,
	
	MIN_MAX_H,
	
	MAX_H,
	MIN_MAX_H_TIMES_CHILDREN_SIZE,
	MIN_MAX_H_POWER_CHILDREN_SIZE,
	
	MIN_SUM_H_ESTIMATED_BRANCHING_FACTOR,
}